global:
  scrape_interval: 15s

scrape_configs:
  - job_name: cargoflow-api
    metrics_path: /metrics
    static_configs:
      - targets: ['integration-api:3001']

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
