CREATE TABLE IF NOT EXISTS cargoflow_integration_audit (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  DEAL_ID INT UNSIGNED NOT NULL,
  EVENT_TYPE VARCHAR(100) NOT NULL,
  RISK_LEVEL VARCHAR(20) NULL,
  PAYLOAD LONGTEXT NULL,
  CREATED_AT DATETIME NOT NULL,
  PRIMARY KEY (ID),
  INDEX IX_CF_AUDIT_DEAL (DEAL_ID),
  INDEX IX_CF_AUDIT_CREATED (CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

